[patch] Add missing property to `VouchersResponse` interface
voucherifyio/voucherify-js-sdk pull request #156
Opened 2022-10-14 17:32 UTC by Davies-Owen

# Change type:

**PATCH**

# Changes

- Add missing `created_at` property to `VouchersResponse` interface

2022-10-17 08:24 UTC, darekg11 requested changes
Rejected, required changes explained in additional comments.
After fixing those, I am more than happy to merge and release new version

2022-10-17 13:30 UTC, darekg11 requested changes
Sorry @Davies-Owen but you forgot to push CHANGESET file, could you please add it?

2022-10-17 13:31 UTC, Davies-Owen commented
I just realized that. It should be there now.

2022-10-18 06:23 UTC, darekg11 approved these changes

2022-10-18 06:27 UTC, merged

2022-10-18 06:33 UTC, darekg11 commented
Hey @Davies-Owen thank you for your contribution.
I have just released version `2.0.17` which includes your changes.
New version should be shortly available in NPM