Loyalties types
voucherifyio/voucherify-js-sdk pull request #21
Opened 2021-01-15 09:03 UTC by pannga

2021-01-27 16:58 UTC, darekg11 requested changes
First round, sorry. Loyalties are huge and doing this in one go is just beyond my capabilities.

Changes requestd:
- compilation error
- merge conflicts
- types, please create couple of different Loyalty campaigns via UI and then list them via API and check properties available.

2021-01-27 16:58 UTC, darekg11 commented on packages/sdk/src/Loyalties.ts
> +	public list(params: T.LoyaltiesListParams) {
It should not be required to pass this `params` since in old SDK it was not required.

2021-01-27 16:58 UTC, darekg11 commented on packages/sdk/src/types/Loyalties.ts
> +	object?: 'list'
Drop `?`

2021-01-27 16:58 UTC, darekg11 commented on packages/sdk/src/types/Loyalties.ts
> +	total?: number
Drop `?`

2021-01-27 16:58 UTC, darekg11 commented on packages/sdk/src/types/Loyalties.ts
> +	data_ref?: 'campaigns'
Drop `?`

2021-01-28 08:44 UTC, pannga commented
I've updated the types - but I have an issue with validation rule assigments in loyalties list response - it should always be empty, as we can't assign validation rule to the Loyalty Campaign, is that correct?

2021-02-08 14:38 UTC, darekg11 requested changes
Let's wait for Voucher Types PR to be merged and then reuse types here.

2021-02-11 09:22 UTC, pannga commented
I've reused Voucher Discount types (maybe I should reuse full voucher? But it will get complicated i guess) and used ValidationRules type.

2021-02-11 14:20 UTC, darekg11 requested changes
Requested changes:
- logic errors
- types errors
- Please create Loyalty campaign with different kind of rewards and reexamine: `LoyaltiesRedeemRewardResponse` type

2021-02-11 14:20 UTC, darekg11 commented on packages/sdk/src/types/Loyalties.ts
> +	object?: string
Drop `?` and it is always `redemption`

2021-02-11 14:20 UTC, darekg11 commented on packages/sdk/src/types/Loyalties.ts
> +	customer_id?: string
Drop `?`

2021-02-11 14:20 UTC, darekg11 commented on packages/sdk/src/types/Loyalties.ts
> +export interface LoyaltiesRedeemRewardResponse {
Missing:
`customer: SimpleCustomer` property

2021-02-11 14:20 UTC, darekg11 commented on packages/sdk/src/types/Loyalties.ts
> +		assignment_id?: string
Drop `?`

2021-02-11 14:20 UTC, darekg11 commented on packages/sdk/src/types/Loyalties.ts
> +		voucher: {
No, most defiinietly it is not always present since you can have material reward.

2021-02-11 14:34 UTC, pannga commented on packages/sdk/src/types/Loyalties.ts
> +export interface LoyaltiesCreateCampaignResponse {
LoyaltiesCreateCampaignResponse has property `created_at` on line 86

2021-02-11 14:58 UTC, pannga commented on packages/sdk/src/types/Loyalties.ts
> +		loyalty?: LoyaltyFixed | LoyaltyProportional | $FixMe
I was not sure if those are all the possible types

2021-02-12 10:13 UTC, pannga commented
Updated :)

2021-02-14 15:17 UTC, darekg11 requested changes
Requested changes:
- types

2021-02-14 15:17 UTC, darekg11 commented on packages/sdk/src/types/Loyalties.ts
> +		type?: 'LOYALTY_CARD'
Drop `?` - it's loyalty campaign creation then not having this field would start returning 400 from server that `discount` property is required which do not make sense for `loyalty`. In other words trying to create loyalty campaign without that field set to `LOYALTY_CARD` is a nonsense.

2021-02-14 15:17 UTC, darekg11 commented on packages/sdk/src/types/Loyalties.ts
> +	order: {
How did you come to the conclusion that `order` is always returned?
I can do request like so:
```
voucherify.loyalties
	.redeemReward("camp_dVpfvCZHgG5iIRdaxXfMtOhl", "v_g4F7aQAjng4kpb6yKjdwjDgM8m36v1im", {
		reward: {
			id: "rew_w63Ju0USU49FcGZ4ZhtxUq6b"
		}
	})
	.then(voucher => {
		console.log('OKS: %j', voucher)
	})
	.catch(error => {
		console.log(error)
	})
```

and it does not return `order` in response. Can't we reuse type from Orders?

2021-02-14 17:57 UTC, pannga commented on packages/sdk/src/Loyalties.ts
> +		return this.client.post<T.LoyaltiesRedeemRewardResponse>(
I did not specified API version (so i guess - v2018). Here is an error I've recieved when I tried to redeem a reward 

```
code: 400,
  details: 'An order is required when redeeming a LOYALTY_CARD',
  key: 'missing_order',
  request_id: 'v-08ca2725f1dd8e3e0f'
```

2021-02-15 08:48 UTC, pannga commented
Updated

2021-02-15 14:51 UTC, darekg11 commented on packages/sdk/src/types/Loyalties.ts
> +		type?: 'LOYALTY_CARD'
Drop `?`

2021-02-15 17:05 UTC, pannga commented
Final updates :100:

2021-02-16 15:05 UTC, darekg11 approved these changes
Merging, thanks for all that work 🙇

2021-02-16 15:06 UTC, merged