Pz/types 010 - loyalties members
voucherifyio/voucherify-js-sdk pull request #238
Opened 2023-09-15 15:33 UTC by p-zielinski

---
'@voucherify/sdk': minor
---

Add support for few endpoints of Loyalties API.
- Added support for new endpoints: `/loyalties/members/{memberId}`, `/loyalties/members/{memberId}/activities`, `/loyalties/members/{memberId}/rewards`, `/loyalties/{campaignId}/members/{memberId}/transfers`, `/loyalties/{campaignId}/members/{memberId}/points-expiration`, `/loyalties/members/{memberId}/transactions`, `/loyalties/{campaignId}/members/{memberId}/transactions`, `/loyalties/members/{memberId}/transactions/export` and `/loyalties/{campaignId}/members/{memberId}/transactions/export` [(examples of usage available in readme.md)](..%2F..%2Fpackages%2Fsdk%2FREADME.md)
- New exported types/interfaces: `ListMemberRewardsParams`, `LoyaltiesListMemberRewardsResponse`, `LoyaltiesTransferPoints`, `GetPointsExpirationParams`, `LoyaltiesGetPointsExpirationResponse`, `ListLoyaltyCardTransactionsParams`, `LoyaltiesListLoyaltyCardTransactionsResponse`, `LoyaltyCardTransactionsType`, `SimpleLoyaltyVoucher`, `LoyaltyCardTransactionsResponse`, `LoyaltyCardTransactionsFields`, `LoyaltiesExportLoyaltyCardTransactionsParams` and `LoyaltiesExportLoyaltyCardTransactionsResponse`

2023-10-03 13:27 UTC, marcin-slezak requested changes
Adjust type names to a new guideline

2023-10-03 13:27 UTC, marcin-slezak commented on packages/sdk/README.md
> +#### [Get Loyalty Program Member Without CampaignId](https://docs.voucherify.io/reference/get-member-1)
Few issues here:
1. The header and method name suggest that we do not need a campaign ID, but you expect it in params and link to documentation where the campaign ID is required.
2. I do not like naming. I understand that we have two similar endpoints, one that expects just member ID and the second one that needs campaign ID in addition. In documentation, both are described as `Get Member`. I guess (but we can confirm it) that the one that needs a campaign ID is a legacy one. We should give a name that will be intuitive for a developer who does not know about the context (legacy method). So, maybe `getMemberById`?

2023-10-03 13:27 UTC, marcin-slezak commented on packages/sdk/README.md
> +client.loyalties.addOrRemoveLoyaltyCardBalance(memberId, balance, campaignId)
Naming: `addOrRemoveLoyaltyCardBalance` -> `addOrRemoveCardBalance`?

2023-10-03 13:27 UTC, marcin-slezak commented on packages/sdk/README.md
> +client.loyalties.listLoyaltyCardTransactions(memberId)
`listLoyaltyCardTransactions` -> `listCardTransactions`?

2023-10-03 13:27 UTC, marcin-slezak commented on packages/sdk/README.md
> +client.loyalties.listLoyaltyCardTransactionsWithCampaignId(campaignId, memberId)
`listLoyaltyCardTransactionsWithCampaignId` -> listTransactionsWithCampaignId`?

2023-10-03 13:27 UTC, marcin-slezak commented on packages/sdk/README.md
> +client.loyalties.exportLoyaltyCardTransactions(memberId, exportLoyaltyCardTransactionsParams)
`exportLoyaltyCardTransactions` -> `exportCardTransactions`?

2023-10-03 13:27 UTC, marcin-slezak commented on packages/sdk/README.md
> +client.loyalties.exportLoyaltyCardTransactionsWithCampaignId(campaignId, memberId, exportLoyaltyCardTransactionsParams)
`exportLoyaltyCardTransactionsWithCampaignId` -> `exportCardTransactionsWithCampaignId`?

2023-10-04 15:11 UTC, p-zielinski commented on packages/sdk/README.md
> +- [[Deprecated] Add Loyalty Card Balance](#add-loyalty-card-balance)
added

2023-10-05 09:53 UTC, marcin-slezak requested changes

2023-10-05 09:53 UTC, marcin-slezak commented on packages/sdk/README.md
> +#### [Add Or Remove Loyalty Card Balance 2](https://docs.voucherify.io/reference/add-remove-loyalty-card-balance-1)
Do not duplicate headers if there are two pages in documentation. Maybe:

```markdown
### [Some header](https://first-link.com)

Depending on the parameters, this method sends requests to [first](https://first-link.com) or [second](https://second-link.com) API endpoint
```

2023-10-05 09:53 UTC, marcin-slezak commented on packages/sdk/src/types/Loyalties.ts
> +export type LoyaltiesTransferPointsResponseBody = LoyaltiesVoucherResponse
try to avoid references to legacy types

2023-10-05 09:53 UTC, marcin-slezak commented on packages/sdk/src/types/Loyalties.ts
> +	data: { reward: RewardsGetResponse; assignment: RewardsAssignmentObject; object: 'loyalty_reward' }[]
formatting, reference to legacy types

2023-10-11 08:24 UTC, marcin-slezak requested changes

2023-10-12 07:50 UTC, marcin-slezak approved these changes

2023-10-12 07:51 UTC, merged