Pz/types 007 - EarningRules
voucherifyio/voucherify-js-sdk pull request #241
Opened 2023-10-04 19:29 UTC by p-zielinski

2023-10-05 07:15 UTC, marcin-slezak requested changes

2023-10-05 07:15 UTC, marcin-slezak commented on packages/sdk/src/types/Loyalties.ts
> +export interface EarningRuleLoyaltyFixed {
I just wonder about the naming - do we need the word `Loyalty` in `EarningRuleLoyaltyFixed` interface name? The same with all names below...

2023-10-05 08:41 UTC, p-zielinski commented on packages/sdk/src/types/Loyalties.ts
will be added in 1h

2023-10-05 13:20 UTC, p-zielinski commented
https://docs.voucherify.io/v2018-08-01-piotr-482/reference/get-earning-rule

2023-10-05 13:20 UTC, p-zielinski commented on packages/sdk/src/types/Loyalties.ts
https://docs.voucherify.io/v2018-08-01-piotr-482/reference/get-earning-rule

2023-10-09 09:15 UTC, marcin-slezak approved these changes

2023-10-09 09:16 UTC, merged