006 - listLoyaltyTierRewards, Reward Assignments methods
voucherifyio/voucherify-js-sdk pull request #249
Opened 2023-10-16 07:29 UTC by weronika-kurczyna

Added support for new endpoints and adding missing types in Rewards API.

Added support for new endpoints: 
- `/loyalties/{campaignId}/rewards/{assignmentId}`,
- `/loyalties/{campaignId}/tiers/{tierId}/rewards` (example available in readme.md)
- `rewards/{rewardId}/assignments/{assignmentId}`

New exported types/interfaces in Loyalties.ts: 
Domain types:
- LoyaltyTierReward, LoyaltyTierRewardItem, LoyaltyTierRewardItemIdentity, LoyaltyTierRewardItemBase, LoyaltyTierRewardItemResponseData, LoyaltyTierRewardItemParameters, LoyaltyTierRewardItemCampaignParameters, LoyaltyTierRewardItemCoinParameters, LoyaltyTierRewardItemMaterialParameters, LoyaltyTierRewardItemCampaignDiscountCoupons, LoyaltyTierRewardItemCampaignGiftVouchersAndLoyaltyProgram
0-level types:
- LoyaltiesGetRewardAssignmentResponseBody, LoyaltiesListLoyaltyTierRewardsResponseBody

New exported types/interfaces in Rewards.ts: 
Domain types:
- RewardAssignment (old `RewardsAssignmentObject`), RewardAssignmentIdentity, RewardAssignmentBase, RewardAssignmentResponseData
0-level types:
- RewardsListAssignmentsRequestQuery (old `RewardsListAssignmentsParams`),
- RewardsListAssignmentsResponseBody (old `RewardsListAssignmentsResponse`), 
- RewardsCreateAssignmentRequestBody (old `RewardsCreateAssignment`), 
- RewardsCreateAssignmentCoinRequestBody, 
- RewardsCreateAssignmentMainRequestBody,
- RewardsCreateAssignmentResponseBody (old `RewardsCreateAssignmentResponse`), 
- RewardsUpdateAssignmentRequestBody (old `RewardsUpdateAssignment`), 
- RewardsUpdateAssignmentResponseBody (old `RewardsUpdateAssignmentResponse`)
- RewardsGetAssignmentResponseBody (brand new)

2023-10-18 09:06 UTC, p-zielinski requested changes

2023-10-18 09:06 UTC, p-zielinski commented on packages/sdk/src/types/Rewards.ts
> +export type RewardsAssignment = Required<RewardAssignmentIdentity> &
we use single-s in domain types?

2023-10-18 09:06 UTC, p-zielinski commented on packages/sdk/src/types/Rewards.ts
> -// domain types
why you have deleted this ? under this line types are new. Domain types, not legacy

2023-10-19 07:48 UTC, p-zielinski requested changes

2023-10-19 07:48 UTC, p-zielinski commented on packages/sdk/src/types/Rewards.ts
> -// domain types
why?

2023-10-19 07:48 UTC, p-zielinski commented on packages/sdk/src/types/Loyalties.ts
>  }
i see above not legacy types...

2023-10-19 07:48 UTC, p-zielinski commented on packages/sdk/src/types/Rewards.ts
> +export interface RewardAssignmentResponseData {
yep

2023-10-19 07:48 UTC, p-zielinski commented on packages/sdk/src/types/Rewards.ts
> +export interface RewardsCreateAssignmentCampaignOrMaterialRewardRequestBody {
does material reward not accept `validation_rules`. ?

2023-10-19 08:28 UTC, weronika-kurczyna commented on packages/sdk/src/types/Rewards.ts
> +export type RewardsAssignment = Required<RewardAssignmentIdentity> &
yep, there was already a type called RewardAssignment and that's why I used another name
but it turns out that `RewardAssignment` can be replaced with a new type, so it is no longer needed (RewardsAssignment was renamed to RewardAssignment)

2023-10-19 13:09 UTC, p-zielinski approved these changes

2023-11-02 12:11 UTC, marcin-slezak commented
released as a part of other RC

2023-11-02 12:11 UTC, closed without merging