Rewards types
voucherifyio/voucherify-js-sdk pull request #28
Opened 2021-01-15 12:51 UTC by pannga

2021-01-22 15:48 UTC, darekg11 commented on packages/sdk/src/Rewards.ts
> +	public list(params: T.RewardsListParams) {
This can be called without any param as per old SDK: pannga:types-rewards

2021-01-22 15:50 UTC, darekg11 commented on packages/sdk/src/types/Rewards.ts
> +	object?: 'list'
Please drop `?`

2021-01-22 15:50 UTC, darekg11 commented on packages/sdk/src/types/Rewards.ts
> +	total?: number
Please drop `?`

2021-01-26 17:42 UTC, darekg11 requested changes
Request changes:
   - types
   - merge conflicts

2021-01-26 17:42 UTC, darekg11 commented on packages/sdk/src/types/Rewards.ts
> +export type RewardsUpdate = RewardsCreate & { id?: string }
It's like Create but you can't overwrite `type` property so please fix as according to comments above and just make sure that "type" can not be passed. Also why `id` has `?` ? For me, it seems like required property in order to update.

2021-01-26 17:42 UTC, darekg11 commented on packages/sdk/src/Rewards.ts
> +	public listAssignments(rewardId: string, params: T.RewardsListAssigmentsParams) {
`params` parameter should not be required and just fallback to `{}` as per old SDK

2021-01-26 17:42 UTC, darekg11 commented on packages/sdk/src/types/Rewards.ts
> +	data_ref?: 'data'
Drop `?`.

2021-01-26 17:42 UTC, darekg11 commented on packages/sdk/src/types/Rewards.ts
> +	id?: string
Please drop `?`

2021-01-26 17:42 UTC, darekg11 commented on packages/sdk/src/types/Rewards.ts
> +	reward_id?: string
Please drop `?`

2021-01-26 17:42 UTC, darekg11 commented on packages/sdk/src/types/Rewards.ts
> +	object?: 'reward_assignment'
Drop `?`

2021-01-26 17:42 UTC, darekg11 commented on packages/sdk/src/types/Rewards.ts
> +	created_at?: string
Drop `?`

2021-01-26 17:42 UTC, darekg11 commented on packages/sdk/src/types/Rewards.ts
> +			points?: number
Drop `?`

2021-01-26 17:42 UTC, darekg11 commented on packages/sdk/src/types/Rewards.ts
> +export type RewardsUpdateAssigment = RewardsCreateAssigment & { id?: string }
Why `id` has `?` ? It seems to me like required property in order to correctly launch update.

2021-01-27 07:45 UTC, pannga commented on packages/sdk/src/types/Rewards.ts
> +		object?: string
I guess the `created_at` is also always provided, so im dropping the `?` on line 18

2021-01-27 09:57 UTC, pannga commented
Hey, I've updated the types accordingly (even with some conditional logic), but I've discovered the `automation_id` property for the `client.rewards.create()` response - it's in the documentation. I can't seem to access this property through API calls. Is this property still exists? 
![Screenshot_2021-01-27 Introduction](https://user-images.githubusercontent.com/19873798/105974718-7933ea00-608e-11eb-980b-67753bd513c2.png)

2021-01-29 11:12 UTC, darekg11 approved these changes

2021-01-29 11:12 UTC, merged