Added Validation Rules types
voucherifyio/voucherify-js-sdk pull request #30
Opened 2021-01-15 14:24 UTC by pannga

2021-01-31 16:48 UTC, darekg11 requested changes
Changes requested:
- merge conflicts
- compilation errors
- types definitions

2021-01-31 16:48 UTC, darekg11 commented on packages/sdk/src/types/ValidationRules.ts
> +export interface ValidationRulesUpdate {
Missing `error` property

2021-01-31 16:48 UTC, darekg11 commented on packages/sdk/src/types/ValidationRules.ts
> +	id?: string
Drop `?`

2021-01-31 16:48 UTC, darekg11 commented on packages/sdk/src/types/ValidationRules.ts
> +	rule_id?: string
Drop `?`

2021-01-31 16:48 UTC, darekg11 commented on packages/sdk/src/types/ValidationRules.ts
> +	created_at?: string
Drop `?`

2021-01-31 16:48 UTC, darekg11 commented on packages/sdk/src/types/ValidationRules.ts
> +	object?: 'validation_rules_assignment'
Drop `?`

2021-01-31 16:48 UTC, darekg11 commented on packages/sdk/src/ValidationRules.ts
> +	// @todo - I can't find any information regarding this method
Drop `TODO`. It's not in API Docs yet.

2021-01-31 16:48 UTC, darekg11 commented on packages/sdk/src/ValidationRules.ts
>  	public validate(validationRuleId: string, params?: $FixMe) {
Use `params = {}`

2021-01-31 16:48 UTC, darekg11 commented on packages/sdk/src/ValidationRules.ts
>  	public validate(validationRuleId: string, params?: $FixMe) {
The type is the same as the one for voucher validation so let's do it later once voucher types PR is mergd

2021-01-31 16:48 UTC, darekg11 commented on packages/sdk/src/ValidationRules.ts
> -		return this.client.post(`/validation-rules/${encode(validationRuleId)}/validation`, params)
Response has following schema:
```
valid: boolean
rule_id: string
applicable_to: {
   data: any[] // let's do it like that for now
   object: "list", 
   total: number
}
```

2021-01-31 16:48 UTC, darekg11 commented on packages/sdk/src/ValidationRules.ts
> +	public list(params: T.ValidationRulesListParams) {
It's not required parameter so please do `= {}`

2021-01-31 16:48 UTC, darekg11 commented on packages/sdk/src/types/ValidationRules.ts
> +	object?: 'list'
Drop `?`

2021-01-31 16:48 UTC, darekg11 commented on packages/sdk/src/types/ValidationRules.ts
> +	total?: number
Drop `?`

2021-01-31 16:48 UTC, darekg11 commented on packages/sdk/src/types/ValidationRules.ts
> +	data_ref?: 'data'
Drop `?`

2021-01-31 16:48 UTC, darekg11 commented on packages/sdk/src/types/ValidationRules.ts
> +export type ValidationRulesListAssigmentsParams = ValidationRulesListParams
Create separate type since it's different entity than ValidationRule

2021-01-31 16:48 UTC, darekg11 commented on packages/sdk/src/ValidationRules.ts
> -	public listAssignments(validationRuleId: string, params: $FixMe) {
`params` is not required so please do `params = {}`

2021-01-31 16:48 UTC, darekg11 commented on packages/sdk/src/types/ValidationRules.ts
> +	object?: 'list'
Drop `?`

2021-01-31 16:48 UTC, darekg11 commented on packages/sdk/src/types/ValidationRules.ts
> +	total?: number
Drop `?`

2021-01-31 16:48 UTC, darekg11 commented on packages/sdk/src/types/ValidationRules.ts
> +	data_ref?: 'data'
Drop `?`

2021-02-01 11:45 UTC, pannga commented
I've updated the types accordingly

2021-02-03 13:53 UTC, merged