Redeem widget
voucherifyio/voucherify-js-sdk pull request #45
Opened 2021-03-19 16:22 UTC by pannga

2021-03-19 16:23 UTC, pannga commented
I've prepated new redeem widget with changes from Publish Widget

2021-03-22 09:33 UTC, darekg11 requested changes
Changes requested:
- 2 small improvements
- 1 logic error

2021-03-22 09:33 UTC, darekg11 commented on packages/react-widget/src/VoucherifyRedeem.tsx
> +import * as React from 'react'
In old SDK `amount` field is not actually required to be entered even after enabling it.

2021-03-22 09:33 UTC, darekg11 commented on packages/react-widget/src/VoucherifyRedeem.tsx
> +import * as React from 'react'
Try widget configuration without setting `amount` property and you won't be able to redeem voucher at all.

2021-03-22 09:35 UTC, darekg11 commented
Oh and if you try to redeem code with white space such as: `TEST THIS` it will convert it to `TESTTHIS` and fail. Is it also happening with publish widget?

2021-03-22 12:11 UTC, pannga commented
Updated. As for this voucher error -> I used wrong regex for this, as it was removing spaces from the string. I'm using this regex in Publish Widget but only for phone numbers.

2021-03-23 07:49 UTC, darekg11 approved these changes
Thanks, working great.

2021-03-23 07:49 UTC, merged