Widgets - Validate
voucherifyio/voucherify-js-sdk pull request #46
Opened 2021-03-23 15:38 UTC by pannga

Fixed some problems with Validate widget + fixed trackingId error

2021-03-24 08:30 UTC, darekg11 requested changes
Does not work at all.
Set it up without amount field and widget ends up sending: `&amount=NaN` and it always comes back with `400 - Bad request`

EDIT: God damnit, nevermind. My bad.

2021-03-24 08:50 UTC, pannga commented
*tips fedora* thank you

2021-03-24 14:55 UTC, pannga commented
I've simplified this app state as @darekg11 requested.

I've also removed this `withCredentials` attribute which I've added here by mistake -> I won't be adding this in the final version (I've talked about this with @pawelrychlik)

I still wait for PR #47 to be merged in order for this PR to pass linting.

2021-03-25 13:53 UTC, pannga commented
@darekg11 I've merged those types and widget is ready for testing.

2021-03-26 09:37 UTC, darekg11 requested changes
Small improvements required.

2021-03-26 09:37 UTC, darekg11 commented on packages/react-widget/src/VoucherifyValidate.tsx
>  import * as React from 'react'
Remove amount input, use gift card, get 400 response but all of the controls are in green color indicating like it was a success while in reality user got 400

2021-03-26 09:37 UTC, darekg11 commented on packages/sdk/src/types/ClientSide.ts
>  	code?: string
Did you rebase your branch on top of master? I don't get why I see the same changes here which already have been applied in previous commit: https://github.com/voucherifyio/voucherify-js-sdk/commit/bf4e2ffdf018c4e6de9d256ea4a25e9b2d280cc6

2021-03-26 09:37 UTC, darekg11 commented on packages/sdk/src/types/Validations.ts
>  	gift?: {
Did you rebase your branch on top of master? I don't get why I see the same changes here which already have been applied in previous commit: bf4e2ff

2021-03-26 09:37 UTC, darekg11 commented on packages/sdk/src/types/ClientSide.ts
> +export interface VoucherifyValidateInputsState {
Let's please move those types which are strictly related to widget to some new file in `packages/react-widget` dir. It does not make sense for someone who only downaloaded SDK package to see those types.

2021-03-26 14:01 UTC, closed without merging